/*
02 Ingreso de Pedidos — auditoría read-only de hora de ingreso
Canales objetivo: 43 y 45
Compatible con SQL Server 2012.

Objetivo:
- explicar "Sin hora válida" del visual de 14:30;
- separar origen ZART vs complemento VBAK;
- distinguir hora vacía, 000000, inválida y válida;
- detectar si VBAK puede recuperar una hora válida cuando ZART no la tiene.

No crea/modifica objetos persistentes. Solo usa tablas temporales de sesión.
*/

SET NOCOUNT ON;

DECLARE @FechaHasta DATE = CAST(GETDATE() AS DATE);
DECLARE @FechaDesde DATE = DATEADD(MONTH, -3, @FechaHasta);

PRINT '=== IN02 / CONTEXTO ===';
SELECT DB_NAME() AS database_name, @FechaDesde AS fecha_desde, @FechaHasta AS fecha_hasta, GETDATE() AS server_now;

IF OBJECT_ID('tempdb..#ZART') IS NOT NULL DROP TABLE #ZART;
IF OBJECT_ID('tempdb..#VBAK') IS NOT NULL DROP TABLE #VBAK;

/* ================================================================
   1) Fuente primaria del modelo: ZART_TRACK_DATA_SAP
      PED = ZERDAT_PED + ZERZET_PED
   ================================================================ */
;WITH Z AS
(
    SELECT
        CONVERT(VARCHAR(20), ZVBELN_PED) AS PEDIDO,
        RIGHT('00' + LTRIM(RTRIM(CONVERT(VARCHAR(10), ZVTGEW))), 2) AS CANAL,
        CONVERT(VARCHAR(30), ZERDAT_PED) AS FECHA_RAW,
        CONVERT(VARCHAR(30), ZERZET_PED) AS HORA_RAW,
        COALESCE
        (
            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERDAT_PED))), ''), 112),
            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERDAT_PED))), ''), 103),
            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERDAT_PED))), ''))
        ) AS FECHA_PARSED,
        NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERZET_PED))), '') AS HORA_TRIM
    FROM dbo.ZART_TRACK_DATA_SAP
),
Z2 AS
(
    SELECT
        Z.*,
        CASE
            WHEN HORA_TRIM IS NULL THEN NULL
            ELSE RIGHT('000000' + REPLACE(HORA_TRIM, ':', ''), 6)
        END AS HORA_6,
        COALESCE
        (
            TRY_CONVERT(TIME(0), HORA_TRIM),
            TRY_CONVERT
            (
                TIME(0),
                CASE
                    WHEN HORA_TRIM IS NULL THEN NULL
                    ELSE STUFF(STUFF(RIGHT('000000' + REPLACE(HORA_TRIM, ':', ''), 6), 3, 0, ':'), 6, 0, ':')
                END
            )
        ) AS HORA_PARSED
    FROM Z
)
SELECT
    PEDIDO,
    CANAL,
    FECHA_RAW,
    HORA_RAW,
    FECHA_PARSED,
    HORA_TRIM,
    HORA_6,
    HORA_PARSED,
    CASE
        WHEN HORA_TRIM IS NULL THEN 'ZART_HORA_NULL_BLANK'
        WHEN HORA_6 = '000000' THEN 'ZART_HORA_000000'
        WHEN HORA_PARSED IS NULL THEN 'ZART_HORA_INVALIDA'
        WHEN HORA_PARSED = CAST('00:00:00' AS TIME(0)) THEN 'ZART_HORA_000000'
        ELSE 'ZART_HORA_VALIDA'
    END AS CAUSA_HORA
INTO #ZART
FROM Z2
WHERE CANAL IN ('43','45')
  AND FECHA_PARSED >= @FechaDesde
  AND FECHA_PARSED < DATEADD(DAY, 1, @FechaHasta)
  AND PEDIDO IS NOT NULL;

PRINT '=== ZART / RESUMEN POR CANAL Y CAUSA ===';
SELECT
    CANAL,
    CAUSA_HORA,
    COUNT(DISTINCT PEDIDO) AS PEDIDOS
FROM #ZART
GROUP BY CANAL, CAUSA_HORA
ORDER BY CANAL, CAUSA_HORA;

PRINT '=== ZART / COBERTURA DE HORA ===';
SELECT
    CANAL,
    COUNT(DISTINCT PEDIDO) AS PEDIDOS_TOTAL,
    COUNT(DISTINCT CASE WHEN CAUSA_HORA = 'ZART_HORA_VALIDA' THEN PEDIDO END) AS PEDIDOS_HORA_VALIDA,
    COUNT(DISTINCT CASE WHEN CAUSA_HORA <> 'ZART_HORA_VALIDA' THEN PEDIDO END) AS PEDIDOS_SIN_HORA_VALIDA,
    CAST(100.0 * COUNT(DISTINCT CASE WHEN CAUSA_HORA = 'ZART_HORA_VALIDA' THEN PEDIDO END)
         / NULLIF(COUNT(DISTINCT PEDIDO), 0) AS DECIMAL(6,2)) AS COBERTURA_HORA_PCT
FROM #ZART
GROUP BY CANAL
ORDER BY CANAL;

/* ================================================================
   2) Fuente secundaria del append: VBAK_SAP
      PED = ERDAT + ERZET
   ================================================================ */
;WITH V AS
(
    SELECT
        CONVERT(VARCHAR(20), VBELN) AS PEDIDO,
        RIGHT('00' + LTRIM(RTRIM(CONVERT(VARCHAR(10), VTWEG))), 2) AS CANAL,
        CONVERT(VARCHAR(30), ERDAT) AS FECHA_RAW,
        CONVERT(VARCHAR(30), ERZET) AS HORA_RAW,
        CONVERT(VARCHAR(20), AUART) AS AUART,
        COALESCE
        (
            TRY_CONVERT(DATE, CONVERT(VARCHAR(30), ERDAT), 112),
            TRY_CONVERT(DATE, CONVERT(VARCHAR(30), ERDAT), 103),
            TRY_CONVERT(DATE, CONVERT(VARCHAR(30), ERDAT))
        ) AS FECHA_PARSED,
        NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ERZET))), '') AS HORA_TRIM
    FROM dbo.VBAK_SAP
    WHERE AUART IN ('ZEDI','ZMAY','ZMAN','ZPDA','ZVGF','ZREL','ZVGM','ZTAN','TAN')
),
V2 AS
(
    SELECT
        V.*,
        CASE
            WHEN HORA_TRIM IS NULL THEN NULL
            ELSE RIGHT('000000' + REPLACE(HORA_TRIM, ':', ''), 6)
        END AS HORA_6,
        COALESCE
        (
            TRY_CONVERT(TIME(0), HORA_TRIM),
            TRY_CONVERT
            (
                TIME(0),
                CASE
                    WHEN HORA_TRIM IS NULL THEN NULL
                    ELSE STUFF(STUFF(RIGHT('000000' + REPLACE(HORA_TRIM, ':', ''), 6), 3, 0, ':'), 6, 0, ':')
                END
            )
        ) AS HORA_PARSED
    FROM V
)
SELECT
    PEDIDO,
    CANAL,
    AUART,
    FECHA_RAW,
    HORA_RAW,
    FECHA_PARSED,
    HORA_TRIM,
    HORA_6,
    HORA_PARSED,
    CASE
        WHEN HORA_TRIM IS NULL THEN 'VBAK_HORA_NULL_BLANK'
        WHEN HORA_6 = '000000' THEN 'VBAK_HORA_000000'
        WHEN HORA_PARSED IS NULL THEN 'VBAK_HORA_INVALIDA'
        WHEN HORA_PARSED = CAST('00:00:00' AS TIME(0)) THEN 'VBAK_HORA_000000'
        ELSE 'VBAK_HORA_VALIDA'
    END AS CAUSA_HORA
INTO #VBAK
FROM V2
WHERE CANAL IN ('43','45')
  AND FECHA_PARSED >= @FechaDesde
  AND FECHA_PARSED < DATEADD(DAY, 1, @FechaHasta)
  AND PEDIDO IS NOT NULL;

PRINT '=== ZART SIN HORA / CRUCE CON VBAK ===';
SELECT
    Z.CANAL,
    Z.CAUSA_HORA AS CAUSA_ZART,
    CASE
        WHEN V.PEDIDO IS NULL THEN 'SIN_VBAK'
        WHEN V.CAUSA_HORA = 'VBAK_HORA_VALIDA' THEN 'VBAK_RECUPERABLE'
        ELSE V.CAUSA_HORA
    END AS ESTADO_VBAK,
    COUNT(DISTINCT Z.PEDIDO) AS PEDIDOS
FROM #ZART AS Z
LEFT JOIN #VBAK AS V
    ON TRY_CONVERT(BIGINT, V.PEDIDO) = TRY_CONVERT(BIGINT, Z.PEDIDO)
WHERE Z.CAUSA_HORA <> 'ZART_HORA_VALIDA'
GROUP BY
    Z.CANAL,
    Z.CAUSA_HORA,
    CASE
        WHEN V.PEDIDO IS NULL THEN 'SIN_VBAK'
        WHEN V.CAUSA_HORA = 'VBAK_HORA_VALIDA' THEN 'VBAK_RECUPERABLE'
        ELSE V.CAUSA_HORA
    END
ORDER BY Z.CANAL, Z.CAUSA_HORA, ESTADO_VBAK;

PRINT '=== MUESTRA ZART SIN HORA + HORA VBAK ===';
SELECT TOP (200)
    Z.PEDIDO,
    Z.CANAL,
    Z.FECHA_RAW AS ZART_FECHA_RAW,
    Z.HORA_RAW AS ZART_HORA_RAW,
    Z.CAUSA_HORA AS ZART_CAUSA,
    V.AUART,
    V.FECHA_RAW AS VBAK_FECHA_RAW,
    V.HORA_RAW AS VBAK_HORA_RAW,
    V.HORA_PARSED AS VBAK_HORA_PARSED,
    V.CAUSA_HORA AS VBAK_CAUSA
FROM #ZART AS Z
LEFT JOIN #VBAK AS V
    ON TRY_CONVERT(BIGINT, V.PEDIDO) = TRY_CONVERT(BIGINT, Z.PEDIDO)
WHERE Z.CAUSA_HORA <> 'ZART_HORA_VALIDA'
ORDER BY Z.CANAL, Z.PEDIDO;

/* Pedidos que podrían entrar por el append VBAK por no existir en ZART. */
PRINT '=== VBAK SIN ZART / RESUMEN POR CANAL Y CAUSA ===';
SELECT
    V.CANAL,
    V.CAUSA_HORA,
    COUNT(DISTINCT V.PEDIDO) AS PEDIDOS
FROM #VBAK AS V
WHERE NOT EXISTS
(
    SELECT 1
    FROM #ZART AS Z
    WHERE TRY_CONVERT(BIGINT, Z.PEDIDO) = TRY_CONVERT(BIGINT, V.PEDIDO)
)
GROUP BY V.CANAL, V.CAUSA_HORA
ORDER BY V.CANAL, V.CAUSA_HORA;

PRINT '=== MUESTRA VBAK SIN ZART Y SIN HORA VALIDA ===';
SELECT TOP (200)
    V.PEDIDO,
    V.CANAL,
    V.AUART,
    V.FECHA_RAW,
    V.HORA_RAW,
    V.HORA_PARSED,
    V.CAUSA_HORA
FROM #VBAK AS V
WHERE NOT EXISTS
(
    SELECT 1
    FROM #ZART AS Z
    WHERE TRY_CONVERT(BIGINT, Z.PEDIDO) = TRY_CONVERT(BIGINT, V.PEDIDO)
)
  AND V.CAUSA_HORA <> 'VBAK_HORA_VALIDA'
ORDER BY V.CANAL, V.PEDIDO;

PRINT '=== RECUPERACION POTENCIAL ===';
SELECT
    Z.CANAL,
    COUNT(DISTINCT Z.PEDIDO) AS ZART_SIN_HORA,
    COUNT(DISTINCT CASE WHEN V.CAUSA_HORA = 'VBAK_HORA_VALIDA' THEN Z.PEDIDO END) AS RECUPERABLE_DESDE_VBAK,
    CAST(100.0 * COUNT(DISTINCT CASE WHEN V.CAUSA_HORA = 'VBAK_HORA_VALIDA' THEN Z.PEDIDO END)
         / NULLIF(COUNT(DISTINCT Z.PEDIDO), 0) AS DECIMAL(6,2)) AS RECUPERABLE_PCT
FROM #ZART AS Z
LEFT JOIN #VBAK AS V
    ON TRY_CONVERT(BIGINT, V.PEDIDO) = TRY_CONVERT(BIGINT, Z.PEDIDO)
WHERE Z.CAUSA_HORA <> 'ZART_HORA_VALIDA'
GROUP BY Z.CANAL
ORDER BY Z.CANAL;

PRINT '=== FIN IN02 HORA INGRESO ===';
