/* DIM_CLIENTE_SQL_CHECK.sql
   Ejecutar en DMF_VTA_PRD para verificar la dimensión de clientes.
   No modifica datos.
*/
SET NOCOUNT ON;
DECLARE @FechaHasta DATE = CAST(GETDATE() AS DATE);
DECLARE @FechaDesde DATE = DATEADD(DAY, -89, @FechaHasta);

;WITH U AS
(
    SELECT
        LTRIM(RTRIM(CONVERT(VARCHAR(30), ZKUNNR))) AS CLIENTE_CODIGO,
        TRY_CONVERT(BIGINT, ZKUNNR) AS CLIENTE_CLAVE,
        RIGHT('00' + LTRIM(RTRIM(CONVERT(VARCHAR(10), ZVTGEW))), 2) AS CANAL,
        COALESCE
        (
            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERDAT_PED))), ''), 112),
            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERDAT_PED))), ''), 103),
            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERDAT_PED))), ''), 105),
            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), ZERDAT_PED))), ''))
        ) AS FECHA_PEDIDO
    FROM dbo.ZART_TRACK_DATA_SAP
    WHERE ZKUNNR IS NOT NULL
)
SELECT 'CLIENTES_UNIVERSO' AS CONTROL, COUNT(DISTINCT CLIENTE_CODIGO) AS CANTIDAD
FROM U
WHERE CANAL IN ('42','43','44','45','46','47')
  AND FECHA_PEDIDO BETWEEN @FechaDesde AND @FechaHasta
UNION ALL
SELECT 'CODIGOS_NO_NUMERICOS', COUNT(*)
FROM
(
    SELECT DISTINCT CLIENTE_CODIGO
    FROM U
    WHERE CANAL IN ('42','43','44','45','46','47')
      AND FECHA_PEDIDO BETWEEN @FechaDesde AND @FechaHasta
      AND CLIENTE_CLAVE IS NULL
) X
UNION ALL
SELECT 'CLIENTES_SIN_KNA1', COUNT(*)
FROM
(
    SELECT DISTINCT U.CLIENTE_CODIGO
    FROM U
    LEFT JOIN dbo.KNA1_SAP K
      ON TRY_CONVERT(BIGINT, K.KUNNR) = U.CLIENTE_CLAVE
    WHERE U.CANAL IN ('42','43','44','45','46','47')
      AND U.FECHA_PEDIDO BETWEEN @FechaDesde AND @FechaHasta
      AND K.KUNNR IS NULL
) X;

-- Duplicados en KNA1 después de normalizar la clave.
SELECT TRY_CONVERT(BIGINT, KUNNR) AS CLIENTE_CLAVE, COUNT(*) AS FILAS
FROM dbo.KNA1_SAP
WHERE KUNNR IS NOT NULL
  AND TRY_CONVERT(BIGINT, KUNNR) IS NOT NULL
GROUP BY TRY_CONVERT(BIGINT, KUNNR)
HAVING COUNT(*) > 1
ORDER BY FILAS DESC;

-- Clientes con más de una asignación de vendedor.
SELECT TRY_CONVERT(BIGINT, VCLT_SUCURSAL) AS CLIENTE_CLAVE, COUNT(*) AS ASIGNACIONES
FROM dbo.CLIENTE_VENDEDOR
WHERE VCLT_SUCURSAL IS NOT NULL
  AND TRY_CONVERT(BIGINT, VCLT_SUCURSAL) IS NOT NULL
GROUP BY TRY_CONVERT(BIGINT, VCLT_SUCURSAL)
HAVING COUNT(*) > 1
ORDER BY ASIGNACIONES DESC;
