table Dim_Cliente
	lineageTag: 7f11bc1c-7498-4998-8dda-a62d380ee02b

	column CLIENTE_CODIGO
		dataType: string
		isKey
		lineageTag: 0d1a83fb-0d57-47b6-a9aa-74c013600f0d
		summarizeBy: none
		sourceColumn: CLIENTE_CODIGO

		annotation SummarizationSetBy = User

	column CLIENTE_CIUDAD
		dataType: string
		lineageTag: a7875b33-fc1f-46b3-9ce4-44eb60ac2cb9
		summarizeBy: none
		sourceColumn: CLIENTE_CIUDAD

		annotation SummarizationSetBy = User

	column CLIENTE_REGION
		dataType: string
		lineageTag: d6fabf0a-c12d-4286-8b0e-0ca4e234edd4
		summarizeBy: none
		sourceColumn: CLIENTE_REGION

		annotation SummarizationSetBy = User

	column CLIENTE_NOMBRE
		dataType: string
		lineageTag: 53ef21e1-e20c-4827-87a5-758d2aa74a01
		summarizeBy: none
		sourceColumn: CLIENTE_NOMBRE

		annotation SummarizationSetBy = User

	column VENDEDOR_NOMBRE
		dataType: string
		lineageTag: 2861c3d5-7799-4df5-9ea6-3744980610e2
		summarizeBy: none
		sourceColumn: VENDEDOR_NOMBRE

		annotation SummarizationSetBy = User

	column CLIENTE_ETIQUETA
		dataType: string
		lineageTag: ac444bad-7bd2-4792-8aee-cf056a5d5b50
		summarizeBy: none
		sourceColumn: CLIENTE_ETIQUETA

		annotation SummarizationSetBy = User

	partition Dim_Cliente = m
		mode: import
		source =
				let
				    Origen =
				        Sql.Database(
				            "128.1.3.21",
				            "DMF_VTA_PRD",
				            [
				                Query = "SET NOCOUNT ON;#(lf)#(lf)DECLARE @FechaHasta DATE = CAST(GETDATE() AS DATE);#(lf)DECLARE @FechaDesde DATE = DATEADD(MONTH, -2, DATEFROMPARTS(YEAR(@FechaHasta), MONTH(@FechaHasta), 1));#(lf)#(lf);WITH PedidosClienteRaw AS#(lf)(#(lf)    SELECT#(lf)        LTRIM(RTRIM(CONVERT(VARCHAR(30), Z.ZKUNNR))) AS CLIENTE_CODIGO,#(lf)        TRY_CONVERT(BIGINT, Z.ZKUNNR) AS CLIENTE_CLAVE_NORMALIZADA,#(lf)        NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(200), Z.ZCITYC))), '') AS CLIENTE_CIUDAD,#(lf)        NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(100), Z.ZREGIO))), '') AS CLIENTE_REGION#(lf)    FROM dbo.ZART_TRACK_DATA_SAP AS Z#(lf)    WHERE Z.ZKUNNR IS NOT NULL#(lf)      AND LTRIM(RTRIM(CONVERT(VARCHAR(30), Z.ZKUNNR))) <> ''#(lf)      AND RIGHT('00' + LTRIM(RTRIM(CONVERT(VARCHAR(10), Z.ZVTGEW))), 2)#(lf)          IN ('42','43','44','45','46','47')#(lf)      AND COALESCE#(lf)          (#(lf)              TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), Z.ZERDAT_PED))), ''), 112),#(lf)              TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), Z.ZERDAT_PED))), ''), 103),#(lf)              TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), Z.ZERDAT_PED))), ''), 105),#(lf)              TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), Z.ZERDAT_PED))), ''))#(lf)          ) BETWEEN @FechaDesde AND @FechaHasta#(lf)),#(lf)PedidosCliente AS#(lf)(#(lf)    SELECT#(lf)        CLIENTE_CODIGO,#(lf)        CLIENTE_CLAVE_NORMALIZADA,#(lf)        MAX(CLIENTE_CIUDAD) AS CLIENTE_CIUDAD,#(lf)        MAX(CLIENTE_REGION) AS CLIENTE_REGION#(lf)    FROM PedidosClienteRaw#(lf)    GROUP BY CLIENTE_CODIGO, CLIENTE_CLAVE_NORMALIZADA#(lf)),#(lf)MaestroCliente AS#(lf)(#(lf)    SELECT#(lf)        TRY_CONVERT(BIGINT, K.KUNNR) AS CLIENTE_CLAVE_NORMALIZADA,#(lf)        MAX(NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(250), K.NAME1))), '')) AS CLIENTE_NOMBRE#(lf)    FROM dbo.KNA1_SAP AS K#(lf)    WHERE K.KUNNR IS NOT NULL#(lf)      AND TRY_CONVERT(BIGINT, K.KUNNR) IS NOT NULL#(lf)    GROUP BY TRY_CONVERT(BIGINT, K.KUNNR)#(lf)),#(lf)VendedorBase AS#(lf)(#(lf)    SELECT#(lf)        TRY_CONVERT(BIGINT, CV.VCLT_SUCURSAL) AS CLIENTE_CLAVE_NORMALIZADA,#(lf)        NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(250), V.VEN_NOMBRE))), '') AS VENDEDOR_NOMBRE,#(lf)        COALESCE#(lf)        (#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_DESDE))), ''), 112),#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_DESDE))), ''), 103),#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_DESDE))), ''), 105),#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_DESDE))), ''))#(lf)        ) AS DESDE_FECHA,#(lf)        COALESCE#(lf)        (#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_HASTA))), ''), 112),#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_HASTA))), ''), 103),#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_HASTA))), ''), 105),#(lf)            TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(CONVERT(VARCHAR(30), CV.VCLT_HASTA))), ''))#(lf)        ) AS HASTA_FECHA#(lf)    FROM dbo.CLIENTE_VENDEDOR AS CV#(lf)    INNER JOIN dbo.VENDEDOR AS V#(lf)        ON V.VEN_COD = CV.VCLT_VEN_COD#(lf)    WHERE CV.VCLT_SUCURSAL IS NOT NULL#(lf)      AND TRY_CONVERT(BIGINT, CV.VCLT_SUCURSAL) IS NOT NULL#(lf)),#(lf)VendedorRank AS#(lf)(#(lf)    SELECT#(lf)        CLIENTE_CLAVE_NORMALIZADA,#(lf)        VENDEDOR_NOMBRE,#(lf)        ROW_NUMBER() OVER#(lf)        (#(lf)            PARTITION BY CLIENTE_CLAVE_NORMALIZADA#(lf)            ORDER BY#(lf)                CASE#(lf)                    WHEN (DESDE_FECHA IS NULL OR DESDE_FECHA <= @FechaHasta)#(lf)                     AND (HASTA_FECHA IS NULL OR HASTA_FECHA >= @FechaHasta)#(lf)                    THEN 0 ELSE 1#(lf)                END,#(lf)                COALESCE(HASTA_FECHA, CONVERT(DATE, '99991231', 112)) DESC,#(lf)                COALESCE(DESDE_FECHA, CONVERT(DATE, '19000101', 112)) DESC,#(lf)                VENDEDOR_NOMBRE ASC#(lf)        ) AS RN#(lf)    FROM VendedorBase#(lf))#(lf)SELECT#(lf)    P.CLIENTE_CODIGO,#(lf)    P.CLIENTE_CIUDAD,#(lf)    P.CLIENTE_REGION,#(lf)    COALESCE(M.CLIENTE_NOMBRE, P.CLIENTE_CODIGO) AS CLIENTE_NOMBRE,#(lf)    VR.VENDEDOR_NOMBRE,#(lf)    CASE#(lf)        WHEN M.CLIENTE_NOMBRE IS NULL OR M.CLIENTE_NOMBRE = '' THEN P.CLIENTE_CODIGO#(lf)        ELSE M.CLIENTE_NOMBRE + ' (' + P.CLIENTE_CODIGO + ')'#(lf)    END AS CLIENTE_ETIQUETA#(lf)FROM PedidosCliente AS P#(lf)LEFT JOIN MaestroCliente AS M#(lf)    ON M.CLIENTE_CLAVE_NORMALIZADA = P.CLIENTE_CLAVE_NORMALIZADA#(lf)LEFT JOIN VendedorRank AS VR#(lf)    ON VR.CLIENTE_CLAVE_NORMALIZADA = P.CLIENTE_CLAVE_NORMALIZADA#(lf)   AND VR.RN = 1#(lf)ORDER BY P.CLIENTE_CODIGO;"
				            ]
				        ),
				    Tipos =
				        Table.TransformColumnTypes(
				            Origen,
				            {
				                {"CLIENTE_CODIGO", type text},
				                {"CLIENTE_CIUDAD", type text},
				                {"CLIENTE_REGION", type text},
				                {"CLIENTE_NOMBRE", type text},
				                {"VENDEDOR_NOMBRE", type text},
				                {"CLIENTE_ETIQUETA", type text}
				            }
				        ),
				    Limpios =
				        Table.TransformColumns(
				            Tipos,
				            {
				                {"CLIENTE_CODIGO", each if _ = null then null else Text.Trim(_), type nullable text},
				                {"CLIENTE_CIUDAD", each if _ = null then null else Text.Trim(_), type nullable text},
				                {"CLIENTE_REGION", each if _ = null then null else Text.Trim(_), type nullable text},
				                {"CLIENTE_NOMBRE", each if _ = null then null else Text.Trim(_), type nullable text},
				                {"VENDEDOR_NOMBRE", each if _ = null then null else Text.Trim(_), type nullable text},
				                {"CLIENTE_ETIQUETA", each if _ = null then null else Text.Trim(_), type nullable text}
				            }
				        ),
				    Filtrados = Table.SelectRows(Limpios, each [CLIENTE_CODIGO] <> null and [CLIENTE_CODIGO] <> ""),
				    Unicos = Table.Distinct(Filtrados, {"CLIENTE_CODIGO"})
				in
				    Unicos

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

