/// Eje desconectado para comparar siempre los tres meses, independientemente del mes elegido en el slicer.
table Dim_Mes_Trend
	lineageTag: 39000000-0000-4000-8000-000000000011

	column PeriodoKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 39000000-0000-4000-8000-000000000012
		summarizeBy: none
		sourceColumn: PeriodoKey

		annotation SummarizationSetBy = User

	column Etiqueta
		dataType: string
		lineageTag: 39000000-0000-4000-8000-000000000013
		summarizeBy: none
		sourceColumn: Etiqueta
		sortByColumn: Orden

		annotation SummarizationSetBy = User

	column AnioMes
		dataType: string
		lineageTag: 39000000-0000-4000-8000-000000000014
		summarizeBy: none
		sourceColumn: AnioMes

		annotation SummarizationSetBy = User

	column Orden
		dataType: int64
		formatString: 0
		lineageTag: 39000000-0000-4000-8000-000000000015
		summarizeBy: none
		sourceColumn: Orden

		annotation SummarizationSetBy = User

	partition Dim_Mes_Trend = m
		mode: import
		source =
				let
				    FechaCorte = Date.From(DateTime.LocalNow()),
				    MesCorte = Date.StartOfMonth(FechaCorte),
				    Offsets = {2, 1, 0},
				    Tabla = Table.FromList(Offsets, Splitter.SplitByNothing(), {"PeriodoKey"}),
				    Tipo = Table.TransformColumnTypes(Tabla, {{"PeriodoKey", Int64.Type}}),
				    Inicio = Table.AddColumn(Tipo, "FechaInicio", each Date.AddMonths(MesCorte, -[PeriodoKey]), type date),
				    AnioMes = Table.AddColumn(Inicio, "AnioMes", each Date.ToText([FechaInicio], "yyyy-MM"), type text),
				    Etiqueta = Table.AddColumn(AnioMes, "Etiqueta", each Text.Proper(Date.MonthName([FechaInicio], "es-CL")) & " " & Date.ToText([FechaInicio], "yyyy"), type text),
				    Orden = Table.AddColumn(Etiqueta, "Orden", each 3 - [PeriodoKey], Int64.Type),
				    Resultado = Table.SelectColumns(Orden, {"PeriodoKey", "Etiqueta", "AnioMes", "Orden"})
				in
				    Resultado

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

