table Fact_Pedidos
	lineageTag: e3d18d01-eedf-4de2-b8a3-e6d8bbdf7079

	column PED_NUMERO_PEDIDO
		dataType: string
		lineageTag: b734d041-131d-4b55-9a95-f5a90478d837
		summarizeBy: none
		sourceColumn: PED_NUMERO_PEDIDO

		annotation SummarizationSetBy = Automatic

	column PED_CODIGO_CLIENTE
		dataType: string
		lineageTag: 3ea41b5d-6935-4ebf-af00-487590073a7f
		summarizeBy: none
		sourceColumn: PED_CODIGO_CLIENTE

		annotation SummarizationSetBy = Automatic

	column PED_RESPONSABLE
		dataType: string
		lineageTag: 6f2f0a81-8df2-4444-9eaa-47584c9bcba0
		summarizeBy: none
		sourceColumn: PED_RESPONSABLE

		annotation SummarizationSetBy = Automatic

	column PED_CENTRO
		dataType: string
		lineageTag: ac57e46e-b025-411a-b9f7-2a9a93a8dbec
		summarizeBy: none
		sourceColumn: PED_CENTRO

		annotation SummarizationSetBy = Automatic

	column PED_CIUDAD
		dataType: string
		lineageTag: 65051861-e044-4fd3-901b-8137affe6df0
		summarizeBy: none
		sourceColumn: PED_CIUDAD

		annotation SummarizationSetBy = Automatic

	column PED_REGION
		dataType: string
		lineageTag: 2049ee31-825f-4c4d-ad37-f89cfa1a48a2
		summarizeBy: none
		sourceColumn: PED_REGION

		annotation SummarizationSetBy = Automatic

	column PED_CONDICION_EXPEDICION_CODIGO
		dataType: string
		lineageTag: 69165222-c0cc-4183-bfc2-dfd754b43e86
		summarizeBy: none
		sourceColumn: PED_CONDICION_EXPEDICION_CODIGO

		annotation SummarizationSetBy = Automatic

	column PED_CONDICION_EXPEDICION
		dataType: string
		lineageTag: 58a588ca-f5e1-4424-a9e7-fe0ea21eb808
		summarizeBy: none
		sourceColumn: PED_CONDICION_EXPEDICION

		annotation SummarizationSetBy = Automatic

	column PED_ORDEN_COMPRA_CLIENTE
		dataType: string
		lineageTag: aa35f3da-c51c-45de-a0e6-f0981d268fb0
		summarizeBy: none
		sourceColumn: PED_ORDEN_COMPRA_CLIENTE

		annotation SummarizationSetBy = Automatic

	column PED_CANAL_CODIGO
		dataType: string
		lineageTag: 45f8e9db-44c0-46af-ae0e-a42d433d8522
		summarizeBy: none
		sourceColumn: PED_CANAL_CODIGO

		annotation SummarizationSetBy = Automatic

	column PED_CANAL
		dataType: string
		lineageTag: 5707eebd-88af-4f4d-b759-8980481f26e7
		summarizeBy: none
		sourceColumn: PED_CANAL

		annotation SummarizationSetBy = Automatic

	column PED_VALOR_NETO
		dataType: decimal
		formatString: "CLP $" #,0;-"CLP $" #,0;"CLP $" 0
		lineageTag: 75be1ab2-3f29-4a64-990c-74b9293c1109
		summarizeBy: sum
		sourceColumn: PED_VALOR_NETO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-CL"}

	column PED_MONEDA
		dataType: string
		lineageTag: 411047fd-9164-49ee-b9c3-5c34200b1afb
		summarizeBy: none
		sourceColumn: PED_MONEDA

		annotation SummarizationSetBy = Automatic

	column PED_BLOQUEO_ENTREGA
		dataType: string
		lineageTag: 533edf09-d9eb-4dcf-a83a-a3d694104506
		summarizeBy: none
		sourceColumn: PED_BLOQUEO_ENTREGA

		annotation SummarizationSetBy = Automatic

	column PED_ESTADO_CREDITO
		dataType: string
		lineageTag: ac61ef1f-cb4e-481c-9cda-0890562d5006
		summarizeBy: none
		sourceColumn: PED_ESTADO_CREDITO

		annotation SummarizationSetBy = Automatic

	column SERV_TIPO_SERVICIO
		dataType: string
		lineageTag: 5b5b54a9-6771-48d4-990f-4a00e12923f8
		summarizeBy: none
		sourceColumn: SERV_TIPO_SERVICIO

		annotation SummarizationSetBy = Automatic

	column SERV_TIPO_SERVICIO_PLANIFICADO
		dataType: string
		lineageTag: e19ec2a7-c4b0-4a96-8478-85e752f0b2a2
		summarizeBy: none
		sourceColumn: SERV_TIPO_SERVICIO_PLANIFICADO

		annotation SummarizationSetBy = Automatic

	column OTIF_ESTADO_PEDIDO
		dataType: string
		lineageTag: 614a17ce-bca1-474b-8452-f9fb46186752
		summarizeBy: none
		sourceColumn: OTIF_ESTADO_PEDIDO

		annotation SummarizationSetBy = Automatic

	column PED_TEXTO_ESTADO
		dataType: string
		lineageTag: deb177d7-b4dc-4d84-8440-b7180ef1399d
		summarizeBy: none
		sourceColumn: PED_TEXTO_ESTADO

		annotation SummarizationSetBy = Automatic

	column ES_FES
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1a2468c9-d54f-4732-a6c7-a002f5521791
		summarizeBy: none
		sourceColumn: ES_FES

		annotation SummarizationSetBy = Automatic

	column ES_SALDO
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7f24a857-8851-4800-a2a5-77082068b2b8
		summarizeBy: none
		sourceColumn: ES_SALDO

		annotation SummarizationSetBy = Automatic

	column SEGMENTO_ANALISIS
		dataType: string
		lineageTag: 9df15f27-e578-462d-b62d-5a461ce0f833
		summarizeBy: none
		sourceColumn: SEGMENTO_ANALISIS

		annotation SummarizationSetBy = Automatic

	column INCLUIR_SLA_NORMAL
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f5a66250-fcb8-474f-95a2-d5f91d64394c
		summarizeBy: none
		sourceColumn: INCLUIR_SLA_NORMAL

		annotation SummarizationSetBy = Automatic

	column PED_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: 3bad72d7-e4f8-4604-9777-41d6498ce569
		summarizeBy: none
		sourceColumn: PED_FECHA_HORA

		annotation SummarizationSetBy = Automatic

	column CRD_P_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b150dfc-1cd2-46c1-9022-ca21e64ef0be
		summarizeBy: none
		sourceColumn: CRD_P_FECHA_HORA

		annotation SummarizationSetBy = Automatic

	column ENT_P_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: fe18c770-2b2a-4d5a-8f51-4a8d8ebd04ff
		summarizeBy: none
		sourceColumn: ENT_P_FECHA_HORA

		annotation SummarizationSetBy = Automatic

	column PIC_P_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: 66554448-cd6b-4c4c-9e12-65aa3cc89982
		summarizeBy: none
		sourceColumn: PIC_P_FECHA_HORA

		annotation SummarizationSetBy = Automatic

	column FAC_P_FECHA_HORA_REAL
		dataType: dateTime
		formatString: General Date
		lineageTag: d6502371-3cfd-4b5e-9429-e46559d9d574
		summarizeBy: none
		sourceColumn: FAC_P_FECHA_HORA_REAL

		annotation SummarizationSetBy = Automatic

	column FAC_U_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: 5e4f3bd5-835c-4934-aa42-167398d6d5a8
		summarizeBy: none
		sourceColumn: FAC_U_FECHA_HORA

		annotation SummarizationSetBy = Automatic

	column TRP_P_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: 12e0b784-16ff-4cbe-bd5b-d9a427774dac
		summarizeBy: none
		sourceColumn: TRP_P_FECHA_HORA

		annotation SummarizationSetBy = Automatic

	column TRP_U_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: c9ea24d5-9808-4a7d-ae7f-c2ed44ddd283
		summarizeBy: none
		sourceColumn: TRP_U_FECHA_HORA

		annotation SummarizationSetBy = Automatic

	column DH_CREDITO_COBRANZAS
		dataType: int64
		formatString: 0
		lineageTag: 7a1ff926-b8de-463f-9f31-2e23e21b3377
		summarizeBy: sum
		sourceColumn: DH_CREDITO_COBRANZAS

		annotation SummarizationSetBy = Automatic

	column DH_OPERACION_INTERNA
		dataType: int64
		formatString: 0
		lineageTag: eec1088f-8ed5-4c96-8c0c-09a7a24d33cf
		summarizeBy: sum
		sourceColumn: DH_OPERACION_INTERNA

		annotation SummarizationSetBy = Automatic

	column DH_CREDITO_A_PRIMERA_ENTREGA
		dataType: int64
		formatString: 0
		lineageTag: 14264b19-7f26-4c66-8ddf-279c71e51a45
		summarizeBy: sum
		sourceColumn: DH_CREDITO_A_PRIMERA_ENTREGA

		annotation SummarizationSetBy = Automatic

	column DH_PRIMERA_ENTREGA_A_PRIMER_PICKING
		dataType: int64
		formatString: 0
		lineageTag: 6252ea60-0813-40b6-90c6-8097812a3322
		summarizeBy: sum
		sourceColumn: DH_PRIMERA_ENTREGA_A_PRIMER_PICKING

		annotation SummarizationSetBy = Automatic

	column DH_PRIMER_PICKING_A_PRIMERA_FACTURA
		dataType: int64
		formatString: 0
		lineageTag: a1335546-9d88-4e06-8d7e-664163ad034e
		summarizeBy: sum
		sourceColumn: DH_PRIMER_PICKING_A_PRIMERA_FACTURA

		annotation SummarizationSetBy = Automatic

	column DH_DESPACHO
		dataType: int64
		formatString: 0
		lineageTag: 190f3209-e06d-421b-aa5e-401fa7fdf2b5
		summarizeBy: sum
		sourceColumn: DH_DESPACHO

		annotation SummarizationSetBy = Automatic

	column DH_LEAD_NORMAL
		dataType: int64
		formatString: 0
		lineageTag: 922c76d8-c655-48b7-90a6-388f74a60bfb
		summarizeBy: sum
		sourceColumn: DH_LEAD_NORMAL

		annotation SummarizationSetBy = Automatic

	column ESTADO_SLA_NORMAL
		dataType: string
		lineageTag: cb0af282-8e0c-402f-806d-779b78991ff2
		summarizeBy: none
		sourceColumn: ESTADO_SLA_NORMAL

		annotation SummarizationSetBy = Automatic

	column PROCESO_DOMINANTE_NORMAL
		dataType: string
		lineageTag: a6d412e3-ca9f-4bdb-a3eb-d94f63ec6d28
		summarizeBy: none
		sourceColumn: PROCESO_DOMINANTE_NORMAL

		annotation SummarizationSetBy = Automatic

	column MES_CREACION
		dataType: string
		lineageTag: 49dd30a5-e7ee-440e-8fb0-66b34381b25c
		summarizeBy: none
		sourceColumn: MES_CREACION

		annotation SummarizationSetBy = Automatic

	column DIA_MES_CREACION
		dataType: int64
		formatString: 0
		lineageTag: eb2568d1-86cd-45d9-9a9e-13466fa76aac
		summarizeBy: sum
		sourceColumn: DIA_MES_CREACION

		annotation SummarizationSetBy = Automatic

	column TRAMO_MES_CALENDARIO
		dataType: string
		lineageTag: 99bffce0-7de8-4c50-b888-854f7941049a
		summarizeBy: none
		sourceColumn: TRAMO_MES_CALENDARIO

		annotation SummarizationSetBy = Automatic

	column ES_ULTIMOS_7_DIAS_HABILES_MES
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 97354492-ad34-42c7-b45a-37bb4008ac30
		summarizeBy: none
		sourceColumn: ES_ULTIMOS_7_DIAS_HABILES_MES

		annotation SummarizationSetBy = Automatic

	column AUD_PCT_COBERTURA_HITOS
		dataType: double
		lineageTag: 9a540910-f840-468e-9d8d-6415aa35a203
		summarizeBy: sum
		sourceColumn: AUD_PCT_COBERTURA_HITOS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AUD_TOTAL_CRITICAS
		dataType: int64
		formatString: 0
		lineageTag: 2110d91c-7792-4b5f-b3f2-6205cfce6cc0
		summarizeBy: sum
		sourceColumn: AUD_TOTAL_CRITICAS

		annotation SummarizationSetBy = Automatic

	column AUD_TOTAL_ADVERTENCIAS
		dataType: int64
		formatString: 0
		lineageTag: bb8e4699-2f8d-47ea-b02f-d227e03e2bb9
		summarizeBy: sum
		sourceColumn: AUD_TOTAL_ADVERTENCIAS

		annotation SummarizationSetBy = Automatic

	column AUD_TOTAL_INCONGRUENCIAS
		dataType: int64
		formatString: 0
		lineageTag: 10d5f204-4110-4401-90b6-2c50d77d08c0
		summarizeBy: sum
		sourceColumn: AUD_TOTAL_INCONGRUENCIAS

		annotation SummarizationSetBy = Automatic

	column AUD_REQUIERE_REVISION
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d6bc1472-e3dc-4e79-8df6-3c07e4784dc8
		summarizeBy: none
		sourceColumn: AUD_REQUIERE_REVISION

		annotation SummarizationSetBy = Automatic

	column AUD_ESTADO_FLUJO_NORMAL
		dataType: string
		lineageTag: 6247732e-ea4d-4713-878a-7bf153a5dadf
		summarizeBy: none
		sourceColumn: AUD_ESTADO_FLUJO_NORMAL

		annotation SummarizationSetBy = Automatic

	column AUD_ESTADO_FLUJO_FES
		dataType: string
		lineageTag: 6c06b5b6-08f5-4dfc-b0fa-e8df73cbc721
		summarizeBy: none
		sourceColumn: AUD_ESTADO_FLUJO_FES

		annotation SummarizationSetBy = Automatic

	column AUD_ESTADO_FLUJO_SALDO
		dataType: string
		lineageTag: ea549dfa-d2d2-43d9-88b4-e913b5393681
		summarizeBy: none
		sourceColumn: AUD_ESTADO_FLUJO_SALDO

		annotation SummarizationSetBy = Automatic

	column AUD_ESTADO_GENERAL
		dataType: string
		lineageTag: 3a706e8c-a5b8-461a-ad83-d228d1330753
		summarizeBy: none
		sourceColumn: AUD_ESTADO_GENERAL

		annotation SummarizationSetBy = Automatic

	column AUD_PRINCIPAL_INCONGRUENCIA
		dataType: string
		lineageTag: 724becd7-6d99-41f9-9472-d4e22e2182ce
		summarizeBy: none
		sourceColumn: AUD_PRINCIPAL_INCONGRUENCIA

		annotation SummarizationSetBy = Automatic

	column PED_FECHA
		dataType: dateTime
		formatString: Long Date
		lineageTag: e2361fbc-7b75-4e0b-ae70-13878f70d6f8
		summarizeBy: none
		sourceColumn: PED_FECHA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PED_ANIO_MES
		dataType: string
		lineageTag: f24a2d5c-db34-49c9-b541-74b8271ebe0d
		summarizeBy: none
		sourceColumn: PED_ANIO_MES

		annotation SummarizationSetBy = Automatic

	column PED_ANIO
		dataType: int64
		formatString: 0
		lineageTag: 2507e528-3df9-4ae3-a953-cfbdb23c6900
		summarizeBy: sum
		sourceColumn: PED_ANIO

		annotation SummarizationSetBy = Automatic

	column PED_MES_NUMERO
		dataType: int64
		formatString: 0
		lineageTag: 21f9ffa1-9a65-4d82-af0f-3fc0e2dfc7d7
		summarizeBy: sum
		sourceColumn: PED_MES_NUMERO

		annotation SummarizationSetBy = Automatic

	column PED_MES_NOMBRE
		dataType: string
		lineageTag: cbcb07fd-e21c-42ce-a000-df22f6b94e03
		summarizeBy: none
		sourceColumn: PED_MES_NOMBRE

		annotation SummarizationSetBy = Automatic

	partition Fact_Pedidos = m
		mode: import
		source =
				let
				    Origen = Fact_Pedidos_Auditoria,
				
				    ColumnasSeleccionadas =
				        Table.SelectColumns(
				            Origen,
				            {
				                // Identificación
				                "PED_NUMERO_PEDIDO",
				                "PED_CODIGO_CLIENTE",
				                "PED_RESPONSABLE",
				                "PED_CENTRO",
				                "PED_CIUDAD",
				                "PED_REGION",
				
				                // Segmentación comercial
				                "PED_CONDICION_EXPEDICION_CODIGO",
				                "PED_CONDICION_EXPEDICION",
				                "PED_ORDEN_COMPRA_CLIENTE",
				                "PED_CANAL_CODIGO",
				                "PED_CANAL",
				
				                // Valores y estados
				                "PED_VALOR_NETO",
				                "PED_MONEDA",
				                "PED_BLOQUEO_ENTREGA",
				                "PED_ESTADO_CREDITO",
				                "SERV_TIPO_SERVICIO",
				                "SERV_TIPO_SERVICIO_PLANIFICADO",
				                "OTIF_ESTADO_PEDIDO",
				                "PED_TEXTO_ESTADO",
				
				                // Clasificación
				                "ES_FES",
				                "ES_SALDO",
				                "SEGMENTO_ANALISIS",
				                "INCLUIR_SLA_NORMAL",
				
				                // Fechas principales
				                "PED_FECHA_HORA",
				                "CRD_P_FECHA_HORA",
				                "ENT_P_FECHA_HORA",
				                "PIC_P_FECHA_HORA",
				                "FAC_P_FECHA_HORA_REAL",
				                "FAC_U_FECHA_HORA",
				                "TRP_P_FECHA_HORA",
				                "TRP_U_FECHA_HORA",
				
				                // Indicadores de tiempo
				                "DH_CREDITO_COBRANZAS",
				                "DH_OPERACION_INTERNA",
				                "DH_CREDITO_A_PRIMERA_ENTREGA",
				                "DH_PRIMERA_ENTREGA_A_PRIMER_PICKING",
				                "DH_PRIMER_PICKING_A_PRIMERA_FACTURA",
				                "DH_DESPACHO",
				                "DH_LEAD_NORMAL",
				
				                // SLA
				                "ESTADO_SLA_NORMAL",
				                "PROCESO_DOMINANTE_NORMAL",
				
				                // Tiempo
				                "MES_CREACION",
				                "DIA_MES_CREACION",
				                "TRAMO_MES_CALENDARIO",
				                "ES_ULTIMOS_7_DIAS_HABILES_MES",
				
				                // Calidad resumida
				                "AUD_PCT_COBERTURA_HITOS",
				                "AUD_TOTAL_CRITICAS",
				                "AUD_TOTAL_ADVERTENCIAS",
				                "AUD_TOTAL_INCONGRUENCIAS",
				                "AUD_REQUIERE_REVISION",
				                "AUD_ESTADO_FLUJO_NORMAL",
				                "AUD_ESTADO_FLUJO_FES",
				                "AUD_ESTADO_FLUJO_SALDO",
				                "AUD_ESTADO_GENERAL",
				                "AUD_PRINCIPAL_INCONGRUENCIA"
				            },
				            MissingField.Error
				        ),
				
				    TipoFechaPedido =
				        Table.AddColumn(
				            ColumnasSeleccionadas,
				            "PED_FECHA",
				            each
				                if [PED_FECHA_HORA] = null
				                then null
				                else Date.From([PED_FECHA_HORA]),
				            type date
				        ),
				
				    TipoAñoMes =
				        Table.AddColumn(
				            TipoFechaPedido,
				            "PED_ANIO_MES",
				            each
				                if [PED_FECHA] = null
				                then null
				                else Date.ToText([PED_FECHA], "yyyy-MM"),
				            type text
				        ),
				
				    TipoAño =
				        Table.AddColumn(
				            TipoAñoMes,
				            "PED_ANIO",
				            each
				                if [PED_FECHA] = null
				                then null
				                else Date.Year([PED_FECHA]),
				            Int64.Type
				        ),
				
				    TipoMesNumero =
				        Table.AddColumn(
				            TipoAño,
				            "PED_MES_NUMERO",
				            each
				                if [PED_FECHA] = null
				                then null
				                else Date.Month([PED_FECHA]),
				            Int64.Type
				        ),
				
				    TipoMesNombre =
				        Table.AddColumn(
				            TipoMesNumero,
				            "PED_MES_NOMBRE",
				            each
				                if [PED_FECHA] = null
				                then null
				                else Date.MonthName([PED_FECHA], "es-CL"),
				            type text
				        ),
				
				    TiposCorregidos =
				        Table.TransformColumnTypes(
				            TipoMesNombre,
				            {
				                {"PED_NUMERO_PEDIDO", type text},
				                {"PED_CODIGO_CLIENTE", type text},
				                {"PED_RESPONSABLE", type text},
				                {"PED_CENTRO", type text},
				                {"PED_CIUDAD", type text},
				                {"PED_REGION", type text},
				                {"PED_CANAL_CODIGO", type text},
				                {"PED_CANAL", type text},
				                {"PED_CONDICION_EXPEDICION_CODIGO", type text},
				                {"PED_CONDICION_EXPEDICION", type text},
				                {"PED_VALOR_NETO", Currency.Type},
				                {"ES_FES", type logical},
				                {"ES_SALDO", type logical},
				                {"INCLUIR_SLA_NORMAL", type logical},
				                {"PED_FECHA_HORA", type datetime},
				                {"CRD_P_FECHA_HORA", type datetime},
				                {"ENT_P_FECHA_HORA", type datetime},
				                {"PIC_P_FECHA_HORA", type datetime},
				                {"FAC_P_FECHA_HORA_REAL", type datetime},
				                {"FAC_U_FECHA_HORA", type datetime},
				                {"TRP_P_FECHA_HORA", type datetime},
				                {"TRP_U_FECHA_HORA", type datetime},
				                {"AUD_PCT_COBERTURA_HITOS", type number},
				                {"AUD_REQUIERE_REVISION", type logical}
				            }
				        ),
				
				    Ordenado =
				        Table.Sort(
				            TiposCorregidos,
				            {
				                {"PED_FECHA_HORA", Order.Ascending},
				                {"PED_NUMERO_PEDIDO", Order.Ascending}
				            }
				        )
				in
				    Ordenado

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

