/// Cartera viva V26. Una fila por pedido del mismo universo Mayorista usado por el resto del modelo.
table Fact_Tracking
	lineageTag: 26000000-0000-4000-8000-000000001000

	column PED_NUMERO_PEDIDO
		dataType: string
		isKey
		lineageTag: 26000000-0000-4000-8000-000000001001
		summarizeBy: none
		sourceColumn: PED_NUMERO_PEDIDO

	column PED_CODIGO_CLIENTE
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001002
		summarizeBy: none
		sourceColumn: PED_CODIGO_CLIENTE

	column PED_RESPONSABLE
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001003
		summarizeBy: none
		sourceColumn: PED_RESPONSABLE

	column PED_CANAL_CODIGO
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001004
		summarizeBy: none
		sourceColumn: PED_CANAL_CODIGO

	column PED_CONDICION_EXPEDICION_CODIGO
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001005
		summarizeBy: none
		sourceColumn: PED_CONDICION_EXPEDICION_CODIGO

	column PED_VALOR_NETO
		dataType: double
		formatString: "CLP $" #,0;-"CLP $" #,0;"CLP $" 0
		lineageTag: 26000000-0000-4000-8000-000000001006
		summarizeBy: sum
		sourceColumn: PED_VALOR_NETO

	column PED_CIUDAD
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001007
		summarizeBy: none
		sourceColumn: PED_CIUDAD

	column PED_REGION
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001008
		summarizeBy: none
		sourceColumn: PED_REGION

	column ZONA
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001009
		summarizeBy: none
		sourceColumn: ZONA

	column CLASIFICACION
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001010
		summarizeBy: none
		sourceColumn: CLASIFICACION

	column PED_FECHA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 26000000-0000-4000-8000-000000001011
		summarizeBy: none
		sourceColumn: PED_FECHA

		annotation UnderlyingDateTimeDataType = Date

	column PED_FECHA_HORA
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001012
		summarizeBy: none
		sourceColumn: PED_FECHA_HORA

	column FECHA_PRIMERA_FACTURA
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001013
		summarizeBy: none
		sourceColumn: FECHA_PRIMERA_FACTURA

	column FECHA_ULTIMA_FACTURA
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001014
		summarizeBy: none
		sourceColumn: FECHA_ULTIMA_FACTURA

	column FECHA_DESPACHO
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001015
		summarizeBy: none
		sourceColumn: FECHA_DESPACHO

	column FECHA_MANIFIESTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001016
		summarizeBy: none
		sourceColumn: FECHA_MANIFIESTO

	column FECHA_CIERRE
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001017
		summarizeBy: none
		sourceColumn: FECHA_CIERRE

	column ES_CERRADO
		dataType: boolean
		formatString: """Sí"";""Sí"";""No"""
		lineageTag: 26000000-0000-4000-8000-000000001018
		summarizeBy: none
		sourceColumn: ES_CERRADO

	column PENDIENTE_FACTURA
		dataType: boolean
		formatString: """Sí"";""Sí"";""No"""
		lineageTag: 26000000-0000-4000-8000-000000001019
		summarizeBy: none
		sourceColumn: PENDIENTE_FACTURA

	column PENDIENTE_DESPACHO
		dataType: boolean
		formatString: """Sí"";""Sí"";""No"""
		lineageTag: 26000000-0000-4000-8000-000000001020
		summarizeBy: none
		sourceColumn: PENDIENTE_DESPACHO

	column ESTADO_ACTUAL
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001021
		summarizeBy: none
		sourceColumn: ESTADO_ACTUAL

	column HITO_ACTUAL
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001022
		summarizeBy: none
		sourceColumn: HITO_ACTUAL

	column FECHA_INICIO_ESTADO
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001023
		summarizeBy: none
		sourceColumn: FECHA_INICIO_ESTADO

	column DIAS_INTERNOS_DH
		dataType: int64
		formatString: 0
		lineageTag: 26000000-0000-4000-8000-000000001024
		summarizeBy: none
		sourceColumn: DIAS_INTERNOS_DH

	column DIAS_EN_ESTADO_DH
		dataType: int64
		formatString: 0
		lineageTag: 26000000-0000-4000-8000-000000001025
		summarizeBy: none
		sourceColumn: DIAS_EN_ESTADO_DH

	column SLA_INTERNO_DH
		dataType: int64
		formatString: 0
		lineageTag: 26000000-0000-4000-8000-000000001026
		summarizeBy: none
		sourceColumn: SLA_INTERNO_DH

	column DIAS_RESTANTES_DH
		dataType: int64
		formatString: 0
		lineageTag: 26000000-0000-4000-8000-000000001027
		summarizeBy: none
		sourceColumn: DIAS_RESTANTES_DH

	column SEMAFORO
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001028
		summarizeBy: none
		sourceColumn: SEMAFORO

	column DIAS_CALENDARIO_SALDO
		dataType: int64
		formatString: 0
		lineageTag: 26000000-0000-4000-8000-000000001029
		summarizeBy: none
		sourceColumn: DIAS_CALENDARIO_SALDO

	column DIAS_HABILES_SALDO
		dataType: int64
		formatString: 0
		lineageTag: 26000000-0000-4000-8000-000000001032
		summarizeBy: none
		sourceColumn: DIAS_HABILES_SALDO

	column VALIDACION_SALDO
		dataType: string
		lineageTag: 26000000-0000-4000-8000-000000001030
		summarizeBy: none
		sourceColumn: VALIDACION_SALDO

	column FECHA_ACTUALIZACION
		dataType: dateTime
		formatString: General Date
		lineageTag: 26000000-0000-4000-8000-000000001031
		summarizeBy: none
		sourceColumn: FECHA_ACTUALIZACION

	partition Fact_Tracking = m
		mode: import
		source =
				let
				    Origen = Fact_Pedidos_Auditoria,
				    FechasPedidoSet = List.RemoveNulls(Origen[PED_FECHA_HORA]),
				    FechaUltimoRegistro = if List.IsEmpty(FechasPedidoSet) then null else List.Max(FechasPedidoSet),
				    Feriados = List.Buffer(List.Transform(Dim_Feriados_Chile[Fecha], each Date.From(_))),
				    // Momento exacto en que Power BI ejecuta la actualización.
				    // Se transforma a la zona local del equipo o gateway que refresca el modelo.
				    AhoraZona = DateTimeZone.ToLocal(DateTimeZone.FixedUtcNow()),
				    Ahora = DateTimeZone.RemoveZone(AhoraZona),
				    Hoy = Date.From(Ahora),
				    FnDH = (Inicio as any, Fin as any) as nullable number =>
				        let
				            I = try Date.From(Inicio) otherwise null,
				            F = try Date.From(Fin) otherwise null,
				            Fechas = if I = null or F = null or F < I then {} else if F = I then {} else List.Dates(Date.AddDays(I, 1), Duration.Days(F-I), #duration(1,0,0,0)),
				            Habiles = List.Select(Fechas, each Date.DayOfWeek(_, Day.Monday) < 5 and not List.Contains(Feriados, _))
				        in if I = null or F = null or F < I then null else List.Count(Habiles),
				    Seleccion = Table.SelectColumns(Origen, {"PED_NUMERO_PEDIDO","PED_CODIGO_CLIENTE","PED_RESPONSABLE","PED_CANAL_CODIGO","PED_CONDICION_EXPEDICION_CODIGO","PED_VALOR_NETO","PED_CIUDAD","PED_REGION","ES_FES","ES_SALDO","PED_FECHA_HORA","CRD_P_FECHA_HORA","ENT_P_FECHA_HORA","PIC_P_FECHA_HORA","PAC_P_FECHA_HORA","FAC_P_FECHA_HORA_REAL","FAC_U_FECHA_HORA","TRP_P_FECHA_HORA","TRP_U_FECHA_HORA","PRIMERA_FECHA_PEDIDO_POSTERIOR","ULTIMA_FECHA_PEDIDO_POSTERIOR","PRIMERA_FECHA_ENTREGA_POSTERIOR","ULTIMA_FECHA_ENTREGA_POSTERIOR","PRIMERA_FECHA_MANIFIESTO","ULTIMA_FECHA_MANIFIESTO"}, MissingField.UseNull),
				    Clasificacion = Table.AddColumn(Seleccion, "CLASIFICACION", each if [ES_FES] = true and [ES_SALDO] = true then "FES + SALDO" else if [ES_FES] = true then "FES" else if [ES_SALDO] = true then "SALDO" else "NORMAL", type text),
				    Zona = Table.AddColumn(Clasificacion, "ZONA", each if Text.TrimStart(Text.Trim(Text.From([PED_REGION])), "0") = "13" then "Santiago" else "Regiones", type text),
				    PedFecha = Table.AddColumn(Zona, "PED_FECHA", each if [PED_FECHA_HORA]=null then null else Date.From([PED_FECHA_HORA]), type nullable date),
				    Fact1 = Table.AddColumn(PedFecha, "FECHA_PRIMERA_FACTURA", each [FAC_P_FECHA_HORA_REAL], type nullable datetime),
				    FactU = Table.AddColumn(Fact1, "FECHA_ULTIMA_FACTURA", each [FAC_U_FECHA_HORA], type nullable datetime),
				    // Regla operativa Santiago: cuando no existe despacho/manifiesto, la factura válida
				    // emitida hasta las 16:00 se considera cierre del mismo día. En Saldo se usa
				    // La última factura; en los demás flujos, la primera factura.
				    FacturaCierre = Table.AddColumn(FactU, "FACTURA_CIERRE_BASE", each if [ES_SALDO]=true and [FECHA_ULTIMA_FACTURA]<>null then [FECHA_ULTIMA_FACTURA] else [FECHA_PRIMERA_FACTURA], type nullable datetime),
				    Desp = Table.AddColumn(FacturaCierre, "FECHA_DESPACHO", each
				        let
				            Real = if [TRP_U_FECHA_HORA]<>null then [TRP_U_FECHA_HORA] else [TRP_P_FECHA_HORA],
				            Factura = [FACTURA_CIERRE_BASE],
				            FechaFactura = if Factura=null then null else Date.From(Factura),
				            HoraFactura = if Factura=null then null else Time.From(Factura),
				            CorteCumplido = FechaFactura<>null and (FechaFactura<Hoy or (FechaFactura=Hoy and Time.From(Ahora)>=#time(16,0,0))),
				            AplicaSantiago = [ZONA]="Santiago" and Factura<>null and HoraFactura<=#time(16,0,0) and CorteCumplido
				        in
				            if Real<>null then Real else if AplicaSantiago then Factura else null,
				        type nullable datetime),
				    Man = Table.AddColumn(Desp, "FECHA_MANIFIESTO", each if [ULTIMA_FECHA_MANIFIESTO]<>null then [ULTIMA_FECHA_MANIFIESTO] else [PRIMERA_FECHA_MANIFIESTO], type nullable datetime),
				    Cierre = Table.AddColumn(Man, "FECHA_CIERRE", each if [ES_FES]=true then (if [FECHA_MANIFIESTO]<>null then [FECHA_MANIFIESTO] else if [ZONA]="Santiago" then [FECHA_DESPACHO] else null) else [FECHA_DESPACHO], type nullable datetime),
				    Cerrado = Table.AddColumn(Cierre, "ES_CERRADO", each [FECHA_CIERRE]<>null, type logical),
				    PendFac = Table.AddColumn(Cerrado, "PENDIENTE_FACTURA", each [FECHA_PRIMERA_FACTURA]=null, type logical),
				    PendDesp = Table.AddColumn(PendFac, "PENDIENTE_DESPACHO", each [FECHA_PRIMERA_FACTURA]<>null and [FECHA_CIERRE]=null, type logical),
				    Estado = Table.AddColumn(PendDesp, "ESTADO_ACTUAL", each if [FECHA_CIERRE]<>null then "CERRADO" else if [FECHA_PRIMERA_FACTURA]=null then "PENDIENTE FACTURA" else if [ES_FES]=true then "PENDIENTE MANIFIESTO FES" else "FACTURADO SIN DESPACHO", type text),
				    Hito = Table.AddColumn(Estado, "HITO_ACTUAL", each if [FECHA_CIERRE]<>null then "CIERRE OPERATIVO" else if [FECHA_PRIMERA_FACTURA]=null and [ENT_P_FECHA_HORA]=null then "ADMINISTRATIVO" else if [FECHA_PRIMERA_FACTURA]=null then "FACTURACIÓN" else if [ES_FES]=true then "MANIFIESTO FES" else "DESPACHO", type text),
				    InicioEstado = Table.AddColumn(Hito, "FECHA_INICIO_ESTADO", each if [FECHA_CIERRE]<>null then [FECHA_CIERRE] else if [FECHA_PRIMERA_FACTURA]=null then (if [ENT_P_FECHA_HORA]<>null then [ENT_P_FECHA_HORA] else [PED_FECHA_HORA]) else [FECHA_PRIMERA_FACTURA], type nullable datetime),
				    DiasInt = Table.AddColumn(InicioEstado, "DIAS_INTERNOS_DH", each FnDH([PED_FECHA_HORA], if [FECHA_CIERRE]<>null then [FECHA_CIERRE] else Ahora), Int64.Type),
				    DiasEstado = Table.AddColumn(DiasInt, "DIAS_EN_ESTADO_DH", each FnDH([FECHA_INICIO_ESTADO], if [FECHA_CIERRE]<>null then [FECHA_CIERRE] else Ahora), Int64.Type),
				    SLA = Table.AddColumn(DiasEstado, "SLA_INTERNO_DH", each 5, Int64.Type),
				    Restantes = Table.AddColumn(SLA, "DIAS_RESTANTES_DH", each if [DIAS_INTERNOS_DH]=null then null else 5-[DIAS_INTERNOS_DH], Int64.Type),
				    Semaforo = Table.AddColumn(Restantes, "SEMAFORO", each if [DIAS_INTERNOS_DH]=null then "REVISAR DATOS" else if [ES_CERRADO] then (if [DIAS_INTERNOS_DH]<=5 then "CERRADO EN SLA" else "CERRADO FUERA SLA") else if [DIAS_RESTANTES_DH]<0 then "VENCIDO" else if [DIAS_RESTANTES_DH]<=1 then "ATENCIÓN" else "EN PLAZO", type text),
				    DiasSaldo = Table.AddColumn(Semaforo, "DIAS_CALENDARIO_SALDO", each if [FECHA_PRIMERA_FACTURA]=null or [FECHA_ULTIMA_FACTURA]=null then null else Duration.Days(Date.From([FECHA_ULTIMA_FACTURA])-Date.From([FECHA_PRIMERA_FACTURA])), Int64.Type),
				    DiasSaldoDH = Table.AddColumn(DiasSaldo, "DIAS_HABILES_SALDO", each if [FECHA_PRIMERA_FACTURA]=null or [FECHA_ULTIMA_FACTURA]=null then null else FnDH([FECHA_PRIMERA_FACTURA], [FECHA_ULTIMA_FACTURA]), Int64.Type),
				    ValSaldo = Table.AddColumn(DiasSaldoDH, "VALIDACION_SALDO", each if [ES_SALDO]=true and ([DIAS_CALENDARIO_SALDO]=null or [DIAS_CALENDARIO_SALDO]<=0) then "REVISAR: BANDERA SIN DIFERENCIA POSITIVA" else if [ES_SALDO]<>true and [DIAS_CALENDARIO_SALDO]<>null and [DIAS_CALENDARIO_SALDO]>0 then "REVISAR: DIFERENCIA POSITIVA SIN BANDERA" else if [ES_SALDO]=true then "SALDO VALIDADO" else "NO SALDO", type text),
				    Actualizacion = Table.AddColumn(ValSaldo, "FECHA_ACTUALIZACION", each FechaUltimoRegistro, type nullable datetime),
				    Resultado = Table.SelectColumns(Actualizacion, {"PED_NUMERO_PEDIDO","PED_CODIGO_CLIENTE","PED_RESPONSABLE","PED_CANAL_CODIGO","PED_CONDICION_EXPEDICION_CODIGO","PED_VALOR_NETO","PED_CIUDAD","PED_REGION","ZONA","CLASIFICACION","PED_FECHA","PED_FECHA_HORA","FECHA_PRIMERA_FACTURA","FECHA_ULTIMA_FACTURA","FECHA_DESPACHO","FECHA_MANIFIESTO","FECHA_CIERRE","ES_CERRADO","PENDIENTE_FACTURA","PENDIENTE_DESPACHO","ESTADO_ACTUAL","HITO_ACTUAL","FECHA_INICIO_ESTADO","DIAS_INTERNOS_DH","DIAS_EN_ESTADO_DH","SLA_INTERNO_DH","DIAS_RESTANTES_DH","SEMAFORO","DIAS_CALENDARIO_SALDO","DIAS_HABILES_SALDO","VALIDACION_SALDO","FECHA_ACTUALIZACION"})
				in
				    Resultado

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

