table Lineas_y_unidades_por_pedidos
	lineageTag: 21f25e76-989d-4d4a-8b83-2b8a9bfa82bd

	column Pedido
		dataType: string
		lineageTag: 7870bffa-e0b1-4497-83df-84d3d1554323
		summarizeBy: none
		sourceColumn: Pedido

		annotation SummarizationSetBy = Automatic

	column Lineas
		dataType: int64
		formatString: 0
		lineageTag: 6366f290-b694-4f05-aced-c26c4d3bd713
		summarizeBy: sum
		sourceColumn: Lineas

		annotation SummarizationSetBy = Automatic

	column Suma_Unidades
		dataType: double
		lineageTag: d14d02c0-070b-40be-aa15-59655703a7ed
		summarizeBy: sum
		sourceColumn: Suma_Unidades

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Lineas_y_unidades_por_pedidos = m
		mode: import
		source =
				let
				    Origen =
				        Sql.Database("128.1.3.21", "DMF_VTA_PRD", [Query="#(lf)                    SELECT#(lf)                        VBAP.VBELN AS Pedido,#(lf)                        COUNT(*) AS Lineas,#(lf)                        SUM(ISNULL(VBAP.KWMENG, 0)) AS Suma_Unidades#(lf)                    FROM VBAP_SAP AS VBAP#(lf)                    WHERE VBAP.AEDAT >= GETDATE() - 730#(lf)                    GROUP BY#(lf)                        VBAP.VBELN#(lf)                    ORDER BY#(lf)                        Suma_Unidades DESC;#(lf)                    "]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Pedido", type text}}),
				
				    TiposDatos =
				        Table.TransformColumnTypes(
				            #"Tipo cambiado",
				            {
				                {"Pedido", type text},
				                {"Lineas", Int64.Type},
				                {"Suma_Unidades", type number}
				            }
				        )
				in
				    TiposDatos

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

