table ML_Comparacion_Modelos
	lineageTag: e5f6a7b8-c9d0-1234-efab-567890123456

	column Modelo
		dataType: string
		lineageTag: f6a7b8c9-d0e1-2345-fabc-678901234567
		summarizeBy: none
		sourceColumn: Modelo

	column Tipo
		dataType: string
		lineageTag: a7b8c9d0-e1f2-3456-abcd-789012345678
		summarizeBy: none
		sourceColumn: Tipo

	column Metrica
		dataType: string
		lineageTag: b8c9d0e1-f2a3-4567-bcde-890123456789
		summarizeBy: none
		sourceColumn: Metrica

	column Valor
		dataType: double
		formatString: 0.0000
		lineageTag: c9d0e1f2-a3b4-5678-cdef-901234567890
		summarizeBy: average
		sourceColumn: Valor

	column Valor_Formateado
		dataType: string
		lineageTag: d0e1f2a3-b4c5-6789-defa-012345678901
		summarizeBy: none
		sourceColumn: Valor_Formateado

	column Diferencia_Absoluta
		dataType: double
		formatString: 0.0000
		lineageTag: e1f2a3b4-c5d6-7890-efab-123456789012
		summarizeBy: average
		sourceColumn: Diferencia_Absoluta

	column Diferencia_Porcentual
		dataType: double
		formatString: 0.0%
		lineageTag: f2a3b4c5-d6e7-8901-fabc-234567890123
		summarizeBy: average
		sourceColumn: Diferencia_Porcentual

	column Veredicto
		dataType: string
		lineageTag: a3b4c5d6-e7f8-9012-abcd-345678901234
		summarizeBy: none
		sourceColumn: Veredicto

	column Split_Info
		dataType: string
		lineageTag: b4c5d6e7-f8a9-0123-bcde-456789012345
		summarizeBy: none
		sourceColumn: Split_Info

	column N_Train
		dataType: int64
		formatString: #,0
		lineageTag: c5d6e7f8-a9b0-1234-cdef-567890123456
		summarizeBy: sum
		sourceColumn: N_Train

	column N_Test
		dataType: int64
		formatString: #,0
		lineageTag: d6e7f8a9-b0c1-2345-defa-678901234567
		summarizeBy: sum
		sourceColumn: N_Test

	column Auditoria_HIST
		dataType: string
		lineageTag: e7f8a9b0-c1d2-3456-efab-789012345678
		summarizeBy: none
		sourceColumn: Auditoria_HIST

	partition ML_Comparacion_Modelos = m
		mode: import
		source =
				let
				    Origen = Fact_Pedidos,
				    Tracking = Fact_Tracking,
				    Python = Python.Execute("import pandas as pd#(lf)import numpy as np#(lf)import warnings#(lf)warnings.filterwarnings('ignore')#(lf)#(lf)try:#(lf)    from sklearn.linear_model import LogisticRegression, Ridge#(lf)    from sklearn.dummy import DummyClassifier, DummyRegressor#(lf)    from sklearn.metrics import roc_auc_score, brier_score_loss, mean_absolute_error, mean_squared_error, r2_score#(lf)    SKLEARN_OK = True#(lf)except Exception:#(lf)    SKLEARN_OK = False#(lf)#(lf)SLA_DH = 5.0#(lf)#(lf)# =====================================================#(lf)# PREPARAR DATOS SIMPLIFICADO#(lf)# =====================================================#(lf)df = pedidos.copy()#(lf)#(lf)# Asegurar que PED_NUMERO_PEDIDO sea string#(lf)df['PED_NUMERO_PEDIDO'] = df['PED_NUMERO_PEDIDO'].astype(str).str.strip()#(lf)#(lf)# Usar DH_LEAD_NORMAL como target (disponible en Fact_Pedidos)#(lf)df['DH_TOTAL'] = pd.to_numeric(df.get('DH_LEAD_NORMAL', np.nan), errors='coerce')#(lf)#(lf)# Filtrar solo pedidos con DH válido y > 0#(lf)df_valid = df[df['DH_TOTAL'].notna() & (df['DH_TOTAL'] > 0) & (df['DH_TOTAL'] <= 60)].copy()#(lf)#(lf)# Clasificar SLA#(lf)df_valid['Y_ATRASO'] = (df_valid['DH_TOTAL'] > SLA_DH).astype(int)#(lf)#(lf)# Preparar features simples#(lf)df_valid['VALOR_NETO'] = pd.to_numeric(df_valid.get('PED_VALOR_NETO', 0), errors='coerce').fillna(0)#(lf)df_valid['VALOR_MM'] = df_valid['VALOR_NETO'] / 1_000_000#(lf)df_valid['ES_FES'] = df_valid.get('ES_FES', False)#(lf)df_valid['ES_SALDO'] = df_valid.get('ES_SALDO', False)#(lf)df_valid['PED_FECHA_HORA'] = pd.to_datetime(df_valid.get('PED_FECHA_HORA'), errors='coerce')#(lf)df_valid['MES'] = df_valid['PED_FECHA_HORA'].dt.strftime('%Y-%m')#(lf)df_valid['DIA_MES'] = df_valid['PED_FECHA_HORA'].dt.day.fillna(0).astype(int)#(lf)#(lf)# Features numéricas simples#(lf)X_num = df_valid[['VALOR_MM', 'DIA_MES']].fillna(0).values#(lf)#(lf)# Features categóricas one-hot#(lf)cat_cols = []#(lf)for c in ['PED_CANAL_CODIGO', 'PED_REGION']:#(lf)    if c in df_valid.columns:#(lf)        df_valid[c] = df_valid[c].astype(str).fillna('SIN DATO')#(lf)        cat_cols.append(c)#(lf)if cat_cols:#(lf)    X_cat = pd.get_dummies(df_valid[cat_cols], drop_first=True, dtype=float).values#(lf)else:#(lf)    X_cat = np.zeros((len(df_valid), 0))#(lf)#(lf)X = np.hstack([X_num, X_cat])#(lf)y_cls = df_valid['Y_ATRASO'].values#(lf)y_reg = df_valid['DH_TOTAL'].values#(lf)#(lf)# =====================================================#(lf)# SPLIT TEMPORAL#(lf)# =====================================================#(lf)if len(df_valid) < 50 or len(np.unique(y_cls)) < 2:#(lf)    # Fallback: devolver tabla vacía con mensaje#(lf)    dataset = pd.DataFrame({#(lf)        'Modelo': ['ERROR'], 'Tipo': ['N/A'], 'Metrica': ['N/A'],#(lf)        'Valor': [0.0], 'Valor_Formateado': ['Datos insuficientes'],#(lf)        'Diferencia_Absoluta': [0.0], 'Diferencia_Porcentual': [0.0],#(lf)        'Veredicto': [f'Solo {len(df_valid)} pedidos válidos, se necesitan ≥50 con 2 clases'],#(lf)        'Split_Info': [f'Total: {len(df)}, Válidos: {len(df_valid)}'],#(lf)        'N_Train': [0], 'N_Test': [0],#(lf)        'Auditoria_HIST': ['DH_LEAD_NORMAL: ' + str(df_valid['DH_TOTAL'].describe().to_dict()) if len(df_valid) > 0 else 'Sin datos']#(lf)    })#(lf)else:#(lf)    months = sorted(df_valid['MES'].dropna().unique())#(lf)    if len(months) >= 3:#(lf)        test_month = months[-2]#(lf)        train_months = months[:-2]#(lf)    elif len(months) >= 2:#(lf)        test_month = months[-1]#(lf)        train_months = months[:-1]#(lf)    else:#(lf)        test_month = months[0]#(lf)        train_months = months#(lf)#(lf)    train_mask = df_valid['MES'].isin(train_months)#(lf)    test_mask = df_valid['MES'].eq(test_month)#(lf)#(lf)    x_train = X[train_mask]#(lf)    x_test = X[test_mask]#(lf)    y_train_cls = y_cls[train_mask]#(lf)    y_test_cls = y_cls[test_mask]#(lf)    y_train_reg = y_reg[train_mask]#(lf)    y_test_reg = y_reg[test_mask]#(lf)#(lf)    # =====================================================#(lf)    # MODELO ML#(lf)    # =====================================================#(lf)    clf_ml = LogisticRegression(max_iter=1000, random_state=42)#(lf)    reg_ml = Ridge(alpha=2.0)#(lf)    clf_ml.fit(x_train, y_train_cls)#(lf)    reg_ml.fit(x_train, y_train_reg)#(lf)#(lf)    p_ml = clf_ml.predict_proba(x_test)[:, 1]#(lf)    d_ml = np.clip(reg_ml.predict(x_test), 0, 60)#(lf)#(lf)    # =====================================================#(lf)    # MODELO BASE#(lf)    # =====================================================#(lf)    clf_base = DummyClassifier(strategy='prior', random_state=42)#(lf)    reg_base = DummyRegressor(strategy='median')#(lf)    clf_base.fit(x_train, y_train_cls)#(lf)    reg_base.fit(x_train, y_train_reg)#(lf)#(lf)    p_base = clf_base.predict_proba(x_test)[:, 1]#(lf)    d_base = np.clip(reg_base.predict(x_test), 0, 60)#(lf)#(lf)    # =====================================================#(lf)    # MÉTRICAS#(lf)    # =====================================================#(lf)    mc_ml = {'AUC': float(roc_auc_score(y_test_cls, p_ml)), 'Brier': float(brier_score_loss(y_test_cls, p_ml))}#(lf)    mr_ml = {'MAE': float(mean_absolute_error(y_test_reg, d_ml)), 'RMSE': float(np.sqrt(mean_squared_error(y_test_reg, d_ml))), 'R2': float(r2_score(y_test_reg, d_ml))}#(lf)    mc_base = {'AUC': float(roc_auc_score(y_test_cls, p_base)), 'Brier': float(brier_score_loss(y_test_cls, p_base))}#(lf)    mr_base = {'MAE': float(mean_absolute_error(y_test_reg, d_base)), 'RMSE': float(np.sqrt(mean_squared_error(y_test_reg, d_base))), 'R2': float(r2_score(y_test_reg, d_base))}#(lf)#(lf)    split_info = f'Train: {len(train_months)} meses ({train_months[0]}..{train_months[-1]}) | Test: {test_month}'#(lf)    n_train = int(x_train.shape[0])#(lf)    n_test = int(x_test.shape[0])#(lf)#(lf)    rows = []#(lf)    for metrica in ['AUC', 'Brier']:#(lf)        v_ml = mc_ml[metrica]#(lf)        v_base = mc_base[metrica]#(lf)        diff = v_ml - v_base#(lf)        pct = diff / abs(v_base) if v_base != 0 else 0#(lf)        mejora = diff > 0 if metrica == 'AUC' else diff < 0#(lf)        rows.append({'Modelo': 'ML', 'Tipo': 'Clasificación', 'Metrica': metrica, 'Valor': v_ml, 'Valor_Formateado': f'{v_ml:.4f}', 'Diferencia_Absoluta': diff, 'Diferencia_Porcentual': pct, 'Veredicto': 'ML SUPERIOR' if mejora else 'BASE SUPERIOR', 'Split_Info': split_info, 'N_Train': n_train, 'N_Test': n_test, 'Auditoria_HIST': ''})#(lf)        rows.append({'Modelo': 'Base (Dummy prior)', 'Tipo': 'Clasificación', 'Metrica': metrica, 'Valor': v_base, 'Valor_Formateado': f'{v_base:.4f}', 'Diferencia_Absoluta': 0, 'Diferencia_Porcentual': 0, 'Veredicto': '', 'Split_Info': '', 'N_Train': 0, 'N_Test': 0, 'Auditoria_HIST': ''})#(lf)    for metrica in ['MAE', 'RMSE', 'R2']:#(lf)        v_ml = mr_ml[metrica]#(lf)        v_base = mr_base[metrica]#(lf)        diff = v_ml - v_base#(lf)        pct = diff / abs(v_base) if v_base != 0 else 0#(lf)        mejora = diff < 0 if metrica in ['MAE', 'RMSE'] else diff > 0#(lf)        rows.append({'Modelo': 'ML', 'Tipo': 'Regresión', 'Metrica': metrica, 'Valor': v_ml, 'Valor_Formateado': f'{v_ml:.4f}', 'Diferencia_Absoluta': diff, 'Diferencia_Porcentual': pct, 'Veredicto': 'ML SUPERIOR' if mejora else 'BASE SUPERIOR', 'Split_Info': split_info, 'N_Train': n_train, 'N_Test': n_test, 'Auditoria_HIST': ''})#(lf)        rows.append({'Modelo': 'Base (Dummy median)', 'Tipo': 'Regresión', 'Metrica': metrica, 'Valor': v_base, 'Valor_Formateado': f'{v_base:.4f}', 'Diferencia_Absoluta': 0, 'Diferencia_Porcentual': 0, 'Veredicto': '', 'Split_Info': '', 'N_Train': 0, 'N_Test': 0, 'Auditoria_HIST': ''})#(lf)    dataset = pd.DataFrame(rows)#(lf)print(f'Comparación completada: {len(dataset)} filas')", [pedidos = Origen, tracking = Tracking]),
				    dataset = Python{[Name="dataset"]}[Value],
				    Tipos = Table.TransformColumnTypes(dataset, {{"Modelo", type text}, {"Tipo", type text}, {"Metrica", type text}, {"Valor", type number}, {"Valor_Formateado", type text}, {"Diferencia_Absoluta", type number}, {"Diferencia_Porcentual", type number}, {"Veredicto", type text}, {"Split_Info", type text}, {"N_Train", Int64.Type}, {"N_Test", Int64.Type}, {"Auditoria_HIST", type text}})
				in
				    Tipos

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

