table ML_Comparacion_Modelos
	lineageTag: e5f6a7b8-c9d0-1234-efab-567890123456

	column Modelo
		dataType: string
		lineageTag: f6a7b8c9-d0e1-2345-fabc-678901234567
		summarizeBy: none
		sourceColumn: Modelo

	column Tipo
		dataType: string
		lineageTag: a7b8c9d0-e1f2-3456-abcd-789012345678
		summarizeBy: none
		sourceColumn: Tipo

	column Metrica
		dataType: string
		lineageTag: b8c9d0e1-f2a3-4567-bcde-890123456789
		summarizeBy: none
		sourceColumn: Metrica

	column Valor
		dataType: double
		formatString: 0.0000
		lineageTag: c9d0e1f2-a3b4-5678-cdef-901234567890
		summarizeBy: average
		sourceColumn: Valor

	column Valor_Formateado
		dataType: string
		lineageTag: d0e1f2a3-b4c5-6789-defa-012345678901
		summarizeBy: none
		sourceColumn: Valor_Formateado

	column Diferencia_Absoluta
		dataType: double
		formatString: 0.0000
		lineageTag: e1f2a3b4-c5d6-7890-efab-123456789012
		summarizeBy: average
		sourceColumn: Diferencia_Absoluta

	column Diferencia_Porcentual
		dataType: double
		formatString: 0.0%
		lineageTag: f2a3b4c5-d6e7-8901-fabc-234567890123
		summarizeBy: average
		sourceColumn: Diferencia_Porcentual

	column Veredicto
		dataType: string
		lineageTag: a3b4c5d6-e7f8-9012-abcd-345678901234
		summarizeBy: none
		sourceColumn: Veredicto

	column Split_Info
		dataType: string
		lineageTag: b4c5d6e7-f8a9-0123-bcde-456789012345
		summarizeBy: none
		sourceColumn: Split_Info

	column N_Train
		dataType: int64
		formatString: #,0
		lineageTag: c5d6e7f8-a9b0-1234-cdef-567890123456
		summarizeBy: sum
		sourceColumn: N_Train

	column N_Test
		dataType: int64
		formatString: #,0
		lineageTag: d6e7f8a9-b0c1-2345-defa-678901234567
		summarizeBy: sum
		sourceColumn: N_Test

	column Auditoria_HIST
		dataType: string
		lineageTag: e7f8a9b0-c1d2-3456-efab-789012345678
		summarizeBy: none
		sourceColumn: Auditoria_HIST

	partition ML_Comparacion_Modelos = m
		mode: import
		source =
				let
				    Base = Table.SelectColumns(Resultado, {"PED_NUMERO_PEDIDO", "DH_TOTAL", "DH_PREDICHO_ML", "PROB_ML_ATRASO", "ES_ENTRENAMIENTO_FINAL", "ES_VALIDACION_TEST", "ES_PENDIENTE"}, MissingField.UseNull),
				    UnaFilaPedido = Table.Distinct(Base, {"PED_NUMERO_PEDIDO"}),
				    TiposEntrada = Table.TransformColumns(UnaFilaPedido, {{"DH_TOTAL", each try Number.From(_) otherwise null, type nullable number}, {"DH_PREDICHO_ML", each try Number.From(_) otherwise null, type nullable number}, {"PROB_ML_ATRASO", each try Number.From(_) otherwise null, type nullable number}}),
				    ValoresRaw = List.RemoveNulls(TiposEntrada[PROB_ML_ATRASO]),
				    MaxAbsRaw = if List.Count(ValoresRaw) = 0 then null else List.Max(List.Transform(ValoresRaw, each Number.Abs(_))),
				    EscalaGlobal = if MaxAbsRaw = null or MaxAbsRaw <= 1 then 1 else Number.Power(10, Number.RoundUp(Number.Log10(MaxAbsRaw))),
				    ConProbNorm = Table.AddColumn(TiposEntrada, "PROB_NORM", each let p = [PROB_ML_ATRASO], v = if p = null then null else p / EscalaGlobal in if v = null or v < 0 or v > 1 then null else v, type nullable number),
				    ConEscala = Table.AddColumn(ConProbNorm, "PROB_ESCALA_GLOBAL", each EscalaGlobal, type number),
				    Python = Python.Execute("import math#(lf)import numpy as np#(lf)import pandas as pd#(lf)#(lf)try:#(lf)    from sklearn.metrics import roc_auc_score, mean_absolute_error, mean_squared_error, r2_score#(lf)    SKLEARN_OK = True#(lf)except Exception:#(lf)    SKLEARN_OK = False#(lf)#(lf)SLA_DH = 5.0#(lf)MAX_DH = 60.0#(lf)#(lf)def as_bool(s):#(lf)    if pd.api.types.is_bool_dtype(s):#(lf)        return s.fillna(False)#(lf)    return s.astype(str).str.strip().str.lower().isin({""true"", ""1"", ""si"", ""sí"", ""yes""})#(lf)#(lf)def auc_seguro(y, p):#(lf)    y = np.asarray(y, dtype=int)#(lf)    p = np.asarray(p, dtype=float)#(lf)    if len(y) == 0 or np.unique(y).size < 2:#(lf)        return np.nan#(lf)    if SKLEARN_OK:#(lf)        return float(roc_auc_score(y, p))#(lf)    order = np.argsort(p)#(lf)    ranks = np.empty_like(order, dtype=float)#(lf)    ranks[order] = np.arange(1, len(p) + 1)#(lf)    pos = y == 1#(lf)    neg = y == 0#(lf)    return float((ranks[pos].sum() - pos.sum() * (pos.sum() + 1) / 2) / (pos.sum() * neg.sum()))#(lf)#(lf)def brier_directo(y, p):#(lf)    y = np.asarray(y, dtype=float)#(lf)    p = np.asarray(p, dtype=float)#(lf)    if len(y) == 0:#(lf)        return np.nan#(lf)    return float(np.mean((y - p) ** 2))#(lf)#(lf)def metricas_regresion(y, pred):#(lf)    y = np.asarray(y, dtype=float)#(lf)    pred = np.asarray(pred, dtype=float)#(lf)    if len(y) == 0:#(lf)        return {""MAE"": np.nan, ""RMSE"": np.nan, ""R2"": np.nan}#(lf)    if SKLEARN_OK:#(lf)        return {#(lf)            ""MAE"": float(mean_absolute_error(y, pred)),#(lf)            ""RMSE"": float(np.sqrt(mean_squared_error(y, pred))),#(lf)            ""R2"": float(r2_score(y, pred)) if len(y) >= 2 else np.nan,#(lf)        }#(lf)    mae = float(np.mean(np.abs(y - pred)))#(lf)    rmse = float(np.sqrt(np.mean((y - pred) ** 2)))#(lf)    denom = float(np.sum((y - y.mean()) ** 2))#(lf)    r2 = float(1 - np.sum((y - pred) ** 2) / denom) if denom > 0 else np.nan#(lf)    return {""MAE"": mae, ""RMSE"": rmse, ""R2"": r2}#(lf)#(lf)def fila(modelo, tipo, metrica, valor, diferencia, pct, veredicto, split, n_train, n_test, auditoria):#(lf)    formateado = ""N/D"" if pd.isna(valor) else f""{float(valor):.4f}""#(lf)    return {#(lf)        ""Modelo"": modelo,#(lf)        ""Tipo"": tipo,#(lf)        ""Metrica"": metrica,#(lf)        ""Valor"": float(valor) if pd.notna(valor) else np.nan,#(lf)        ""Valor_Formateado"": formateado,#(lf)        ""Diferencia_Absoluta"": float(diferencia) if pd.notna(diferencia) else np.nan,#(lf)        ""Diferencia_Porcentual"": float(pct) if pd.notna(pct) else np.nan,#(lf)        ""Veredicto"": veredicto,#(lf)        ""Split_Info"": split,#(lf)        ""N_Train"": int(n_train),#(lf)        ""N_Test"": int(n_test),#(lf)        ""Auditoria_HIST"": auditoria,#(lf)    }#(lf)#(lf)df = resultado.copy()#(lf)requeridas = [#(lf)    ""PED_NUMERO_PEDIDO"", ""DH_TOTAL"", ""DH_PREDICHO_ML"", ""PROB_NORM"",#(lf)    ""PROB_ESCALA_GLOBAL"", ""ES_ENTRENAMIENTO_FINAL"", ""ES_VALIDACION_TEST"", ""ES_PENDIENTE"",#(lf)]#(lf)faltantes = [c for c in requeridas if c not in df.columns]#(lf)#(lf)if faltantes:#(lf)    dataset = pd.DataFrame([#(lf)        fila(""ERROR"", ""N/A"", ""N/A"", np.nan, np.nan, np.nan, ""COLUMNAS FALTANTES"", """", 0, 0, "","".join(faltantes))#(lf)    ])#(lf)else:#(lf)    df[""PED_NUMERO_PEDIDO""] = df[""PED_NUMERO_PEDIDO""].astype(str).str.strip()#(lf)    df = df.drop_duplicates(""PED_NUMERO_PEDIDO"", keep=""last"").copy()#(lf)    df[""DH_TOTAL""] = pd.to_numeric(df[""DH_TOTAL""], errors=""coerce"")#(lf)    df[""DH_PREDICHO_ML""] = pd.to_numeric(df[""DH_PREDICHO_ML""], errors=""coerce"")#(lf)    df[""PROB""] = pd.to_numeric(df[""PROB_NORM""], errors=""coerce"")#(lf)    df[""PROB_ESCALA_GLOBAL""] = pd.to_numeric(df[""PROB_ESCALA_GLOBAL""], errors=""coerce"")#(lf)    df[""ES_ENTRENAMIENTO_FINAL""] = as_bool(df[""ES_ENTRENAMIENTO_FINAL""])#(lf)    df[""ES_VALIDACION_TEST""] = as_bool(df[""ES_VALIDACION_TEST""])#(lf)    df[""ES_PENDIENTE""] = as_bool(df[""ES_PENDIENTE""])#(lf)#(lf)    valid = (#(lf)        df[""ES_ENTRENAMIENTO_FINAL""]#(lf)        & ~df[""ES_PENDIENTE""]#(lf)        & df[""DH_TOTAL""].between(0, MAX_DH, inclusive=""both"")#(lf)    )#(lf)    df[""Y_ATRASO_SLA_5DH""] = np.where(valid, (df[""DH_TOTAL""] > SLA_DH).astype(int), np.nan)#(lf)    train = df.loc[valid & ~df[""ES_VALIDACION_TEST""]].copy()#(lf)    test = df.loc[valid & df[""ES_VALIDACION_TEST""]].copy()#(lf)#(lf)    n_train, n_test = len(train), len(test)#(lf)    pos_train = int(train[""Y_ATRASO_SLA_5DH""].sum()) if n_train else 0#(lf)    pos_test = int(test[""Y_ATRASO_SLA_5DH""].sum()) if n_test else 0#(lf)    tasa_train = pos_train / n_train if n_train else np.nan#(lf)    tasa_test = pos_test / n_test if n_test else np.nan#(lf)    escala = float(df[""PROB_ESCALA_GLOBAL""].dropna().iloc[0]) if df[""PROB_ESCALA_GLOBAL""].notna().any() else 1.0#(lf)#(lf)    split = f""Train={n_train} ({pos_train} fuera SLA, {tasa_train:.4%}) | Test={n_test} ({pos_test} fuera SLA, {tasa_test:.4%})""#(lf)    auditoria = f""TARGET=DH_TOTAL>5; ESCALA_GLOBAL={escala:.0f}; BRIER=MEDIA((Y-P)^2); FUENTE=Resultado""#(lf)#(lf)    if n_train == 0 or n_test == 0:#(lf)        dataset = pd.DataFrame([#(lf)            fila(""ERROR"", ""N/A"", ""N/A"", np.nan, np.nan, np.nan, ""SPLIT VACÍO"", split, n_train, n_test, auditoria)#(lf)        ])#(lf)    else:#(lf)        test_cls = test.dropna(subset=[""PROB"", ""Y_ATRASO_SLA_5DH""]).copy()#(lf)        test_cls = test_cls.loc[test_cls[""PROB""].between(0, 1, inclusive=""both"")]#(lf)        y_test = test_cls[""Y_ATRASO_SLA_5DH""].astype(int).to_numpy()#(lf)        p_ml = test_cls[""PROB""].astype(float).to_numpy()#(lf)        p_base = np.full(len(test_cls), tasa_train, dtype=float)#(lf)#(lf)        auc_ml = auc_seguro(y_test, p_ml)#(lf)        auc_base = auc_seguro(y_test, p_base)#(lf)        brier_ml = brier_directo(y_test, p_ml)#(lf)        brier_base = brier_directo(y_test, p_base)#(lf)#(lf)        mediana_train = float(train[""DH_TOTAL""].median())#(lf)        test_reg = test.dropna(subset=[""DH_TOTAL"", ""DH_PREDICHO_ML""]).copy()#(lf)        y_reg = test_reg[""DH_TOTAL""].astype(float).to_numpy()#(lf)        d_ml = np.clip(test_reg[""DH_PREDICHO_ML""].astype(float).to_numpy(), 0, MAX_DH)#(lf)        d_base = np.full(len(test_reg), mediana_train, dtype=float)#(lf)        reg_ml = metricas_regresion(y_reg, d_ml)#(lf)        reg_base = metricas_regresion(y_reg, d_base)#(lf)#(lf)        rows = []#(lf)        for metrica, v_ml, v_base, mayor_mejor in [#(lf)            (""AUC"", auc_ml, auc_base, True),#(lf)            (""Brier"", brier_ml, brier_base, False),#(lf)        ]:#(lf)            diff = v_ml - v_base if pd.notna(v_ml) and pd.notna(v_base) else np.nan#(lf)            pct = diff / abs(v_base) if pd.notna(diff) and pd.notna(v_base) and v_base != 0 else np.nan#(lf)            mejora = (diff > 0) if mayor_mejor and pd.notna(diff) else ((diff < 0) if pd.notna(diff) else False)#(lf)            rows.append(fila(""ML"", ""Clasificación"", metrica, v_ml, diff, pct, ""ML SUPERIOR"" if mejora else ""BASE SUPERIOR"", split, n_train, n_test, auditoria))#(lf)            rows.append(fila(""Base (prior)"", ""Clasificación"", metrica, v_base, 0.0, 0.0, """", """", 0, 0, auditoria))#(lf)#(lf)        for metrica in [""MAE"", ""RMSE"", ""R2""]:#(lf)            v_ml, v_base = reg_ml[metrica], reg_base[metrica]#(lf)            diff = v_ml - v_base if pd.notna(v_ml) and pd.notna(v_base) else np.nan#(lf)            pct = diff / abs(v_base) if pd.notna(diff) and pd.notna(v_base) and v_base != 0 else np.nan#(lf)            mejora = (diff > 0) if metrica == ""R2"" and pd.notna(diff) else ((diff < 0) if pd.notna(diff) else False)#(lf)            rows.append(fila(""ML"", ""Regresión"", metrica, v_ml, diff, pct, ""ML SUPERIOR"" if mejora else ""BASE SUPERIOR"", split, n_train, n_test, auditoria))#(lf)            rows.append(fila(""Base (mediana)"", ""Regresión"", metrica, v_base, 0.0, 0.0, """", """", 0, 0, auditoria))#(lf)        dataset = pd.DataFrame(rows)#(lf)#(lf)for c in [""Valor"", ""Diferencia_Absoluta"", ""Diferencia_Porcentual""]:#(lf)    if c in dataset.columns:#(lf)        dataset[c] = pd.to_numeric(dataset[c], errors=""coerce"").astype(""float64"")", [resultado = ConEscala]),
				    dataset = Python{[Name="dataset"]}[Value],
				    Tipos = Table.TransformColumnTypes(dataset, {{"Modelo", type text}, {"Tipo", type text}, {"Metrica", type text}, {"Valor", type number}, {"Valor_Formateado", type text}, {"Diferencia_Absoluta", type number}, {"Diferencia_Porcentual", type number}, {"Veredicto", type text}, {"Split_Info", type text}, {"N_Train", Int64.Type}, {"N_Test", Int64.Type}, {"Auditoria_HIST", type text}})
				in
				    Tipos

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

